apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web2048-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vijaysexena/aks-2048-cicd.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
