apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2048-autoscaler
  namespace: kubernetes
  labels:
    app: web2048-autoscaler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2048-autoscaler
  template:
    metadata:
      labels:
        app: web2048-autoscaler
    spec:
      containers:
      - name: web2048-autoscaler
        # image: yourACRname.azurecr.io/web2048-autoscaler:latest
        image: saxenavijay62/web2048-autoscaler:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: regcred  
