apiVersion: v1
kind: Service
metadata:
  name: web2048-autoscaler-service
  namespace: kubernetes
spec:
  selector:
    app: web2048-autoscaler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer


#####