# # name: Build, Push & Deploy to AKS

# # on:
# #   push:
# #     branches:
# #       - main

# # env:
# #   ACR_NAME: vijayacr2025     
# #   RESOURCE_GROUP: azure-eks      
# #   AKS_CLUSTER_NAME: azure-aks   
# #   K8S_NAMESPACE: kubernetes

# # jobs:
# #   build-push-deploy:
# #     runs-on: ubuntu-latest

# #     steps:
# #     - name: Checkout repo
# #       uses: actions/checkout@v3

# #     - name: Log in to Azure CLI
# #       uses: azure/login@v1
# #       with:
# #         creds: ${{ secrets.AZURE_CREDENTIALS }}

# #     - name: Get AKS credentials
# #       run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

# #     - name: Log in to ACR
# #       uses: azure/docker-login@v1
# #       with:
# #         login-server: ${{ env.ACR_NAME }}.azurecr.io
# #         username: ${{ secrets.ACR_USERNAME }}
# #         password: ${{ secrets.ACR_PASSWORD }}

# #     - name: Build and push Docker image
# #       run: |
# #         IMAGE_TAG=${{ github.sha }}
# #         docker build -t $ACR_NAME.azurecr.io/web2048-autoscaler:$IMAGE_TAG .
# #         docker push $ACR_NAME.azurecr.io/web2048-autoscaler:$IMAGE_TAG

# #     - name: Deploy to AKS
# #       run: |
# #         kubectl set image deployment/web2048-autoscaler web2048-autoscaler=$ACR_NAME.azurecr.io/web2048-autoscaler:${{ github.sha }} -n $K8S_NAMESPACE
# #         kubectl rollout status deployment/web2048-autoscaler -n $K8S_NAMESPACE


# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)



name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: web2048-autoscaler
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CLUSTER_NAME: azure-aks
  RESOURCE_GROUP: azure-eks
  NAMESPACE: kubernetes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl apply -f k8s/hpa.yml
